### ISSUE TITLE
Issue configuring Prosper

### ISSUE THREAD

**Issue by viveksachdeva** [Citytechinc/prosper#8]
I have modified to include dependencies mentioned in the README.. When running tests, I am getting following error:
ExampleSpec  Time elapsed: 1.395 sec  <<< ERROR!
java.lang.NoClassDefFoundError: org/slf4j/helpers/NOPLoggerFactory
Caused by: java.lang.ClassNotFoundException: org.slf4j.helpers.NOPLoggerFactory

ExampleSpec  Time elapsed: 1.396 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class com.icfolson.aem.groovy.extension.metaclass.GroovyExtensionMetaClassRegistry

**Comment by lykorian** [comment]
This is fixed in 8.1.1.
